### ISSUE TITLE
CSS variables not supported

### ISSUE THREAD

**Issue by scottaddie** [xoofx/NUglify#17]
[CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) don't seem to be supported. For example, try minifying a CSS file with the following content:

```css
:root {
--background:#006b6b;
--textcolour:#ffffff;
--hoverOverColour:#FFC100;
--gradientDarkColour:#004a4a;
--gradienDarkHoverColour:#005a5a;
--gradientLightColour:#008b8b;
--gradientLightHoverColour:#009b9b;
--topMenuTextColour:#003b3b;
}
```

The following error occurs for each of the 8 variables defined above: **Expected semicolon or closing curly-brace, found '-'**. I'm using version 1.5.1 of the NuGet package when I encounter this error.
