### ISSUE TITLE
Minifying css with @support and a 'or' statement removes necessary whitespace.

### ISSUE THREAD

**Issue by cabralRodrigo** [xoofx/NUglify#58]
Minifying the following css:

```csharp
var css = @"@supports ((position: -webkit-sticky) or (position:sticky)) {
                body { background-color: red; }
            }";

var result = Uglify.Css(css);
```

Outputs:
```css
@supports((position:-webkit-sticky)or(position:sticky)){body{background-color:red;}}
```

When the correct output would be:
```css
@supports((position:-webkit-sticky) or (position:sticky)){body{background-color:red;}}
```
